spring:
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect

  elasticsearch:
    uris: ${ES_URI}
    username: ${ES_USERNAME}
    password: ${ES_PASSWORD}

libray:
  api:
    key: ${LIBRARY_API_KEY}

logging:
  level:
    root: info
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.jdbc.core.StatementCreatorUtils: trace