spring:
  application:
    name: bookKing
  profiles:
    default: release
  web:
    resources:
      add-mappings: false

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    jmx:
      exposure:
        include: health
