spring:
  application:
    name: bookKing
  profiles:
    default: dev

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    jmx:
      exposure:
        include: health

  jwt:
    secret:
      key: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff