server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s # default

  datasource:
    hikari:
      writer:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${WRITER_URL}:3306/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
      reader:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${READER_URL}:3306/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  elasticsearch:
    uris: ${ES_URI}
    username: ${ES_USERNAME}
    password: ${ES_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${S3_REGION}

elasticsearch:
  uris: ${ES_URI}
  username: ${ES_USERNAME}
  password: ${ES_PASSWORD}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

library:
  api:
    key: ${LIBRARY_API_KEY}