name: 테스트 및 빌드

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java 17 setup
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Gradle setup
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Clean and build gradle
        run: ./gradlew clean build

      - name: Jacoco report when open PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 50
          min-coverage-changed-files: 50
          title: Code Coverage
          update-comment: true

      - name: Upload jacoco HTML report
        uses: actions/upload-artifact@v4
        with:
          name: 'Jacoco HTML Report'
          path: ${{ github.workspace }}/build/reports/jacoco/test/html

      - name: Get the Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"

  slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: send to notice from slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,author,workflow,job,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()